% ?Copyright 2015 Shon Schmidt
% 
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, version 3 of the License.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
% 
% You should have received a copy of the GNU Lesser General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.

% obj is the main testbench object
% --- build up a optical stage control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013

function obj = edge_coupled_stage_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
move_button_x = 0.075;
move_button_y = 0.175;

control_button_x = 0.2;
control_button_y = 0.175;

edit_x = 0.2;
edit_y = 0.175;

% optical stage parent panel
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel = uipanel(...
    'Parent', parentObj, ...
    'Unit','Pixels', ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Edge coupled fiber stage', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

%% Movement Buttons section

% X Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dStaticXStepOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.085, .8, .2, .12], ...
    'String','X (steps)', ...
    'FontSize', 9);

% X Left Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dXLeftButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .8, move_button_x, move_button_y], ...
    'String','<', ...
    'Callback', {@dXLeftButtonOC_cb, obj, parentStruct, panelIndex});

% X Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dXStepSizeOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.34, .8, edit_x, edit_y], ...
    'String',100);

% X Right Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dXRightButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.55, .8, move_button_x, move_button_y], ...
    'String','>', ...
    'Callback', {@dXRightButtonOC_cb, obj, parentStruct, panelIndex});

% Y Step Size Static OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dStaticYStepOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.085, .6, .2, .12], ...
    'String','Y (steps)', ...
    'FontSize', 9);

% Y Left Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dYLeftButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .6, move_button_x, move_button_y], ...
    'String','^', ...
    'Callback', {@dYLeftButtonOC_cb, obj, parentStruct, panelIndex});

% Y Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dYStepSizeOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.34, .6, edit_x, edit_y], ...
    'String',1000);

%Y Right Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dYRightButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.55, .6, move_button_x, move_button_y], ...
    'String','v', ...
    'Callback', {@dYRightButtonOC_cb, obj, parentStruct, panelIndex});

% yRotation Step Size Static OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dyRotationStepOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.04, .4, .2, .16], ...
    'String', 'Y Rot (steps)', ...
    'FontSize', 9);
%    'String', sprintf('Y Rotation (%c)', char(176)), ...

% yRotation Left Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dxRotationLeftOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .4, move_button_x, move_button_y], ...
    'String','+', ...
    'Callback', {@dyRotationLeftOC_cb, obj, parentStruct, panelIndex});

% yRotation Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dyRotationStepSizeOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.34, .4, edit_x, edit_y], ...
    'String',1000);

% yRotation Right Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dxRotationRightOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.55, .4, move_button_x, move_button_y], ...
    'String','-', ...
    'Callback', {@dxRotationRightOC_cb, obj, parentStruct, panelIndex});

% Z Step Size Static OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dStaticZStepOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.085, .2, .2, .12], ...
    'String','Z (steps)', ...
    'FontSize', 9);

% Z Left Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZLeftButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .2, move_button_x, move_button_y], ...
    'String','v', ...
    'Callback', {@dZLeftButtonOC_cb, obj, parentStruct, panelIndex});

% Z Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZStepSizeOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.34, .2, edit_x, edit_y], ...
    'String',1000);

% Z Right Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZRightButtonOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.55, .2, move_button_x, move_button_y], ...
    'String','^', ...
    'Callback', {@dZRightButtonOC_cb, obj, parentStruct, panelIndex});

% zRotation Step Size Static OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dStaticzRotationStepOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.043, .0, .2, .16], ...
	'String', 'Z Rot (steps)',...
    'FontSize', 9);
%    'String', sprintf('zRotation(%c)', char(176)), ...

% zRotation Left Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dzRotationLeftOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .0, move_button_x, move_button_y], ...
    'String','+', ...
    'Callback', {@dzRotationLeftOC_cb, obj, parentStruct, panelIndex});

% zRotation Step Size OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dzRotationStepSizeOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.34, .0, edit_x, edit_y], ...
    'String',1000);

% zRotation Right Button OC
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dzRotationRightOC = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.55, .0, move_button_x, move_button_y], ...
    'String','-', ...
    'Callback', {@dzRotationRightOC_cb, obj, parentStruct, panelIndex});


% Optical Settings Button
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dSettingsOptical = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable', 'off', ...
    'Units', 'normalized', ...
    'Position', [.7, .8, control_button_x, control_button_y], ...
    'String','Settings', ...
    'Callback',{@dSettingsOptical_cb, obj});

% % Calibrate Button
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dCalibrateOpticalStage = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','pushbutton', ...
%     'Enable', 'off', ...
%     'Units', 'normalized', ...
%     'Position', [.7, .73, control_button_x, control_button_y], ...
%     'String','Calibrate', ...
%     'Callback',{@CalibrateOpticalStage_cb, obj});

% % Lock Button
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dLockOpticalStage = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','pushbutton', ...
%     'Enable', 'on', ...
%     'Units', 'normalized', ...
%     'Position', [.7, .59, control_button_x, control_button_y], ...
%     'String','Lock Z', ...
%     'Callback',{@LockOpticalStage_cb, obj, parentStruct, panelIndex});

% % Eject Button
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.ejectButton = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','pushbutton', ...
%     'Enable','on', ...
%     'Units', 'normalized', ...
%     'Position', [.7, .45, control_button_x, control_button_y], ...
%     'String','Eject', ...
%     'Callback',{@eject_button_cb, obj, parentStruct, panelIndex});
% 
% % Load Button
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.loadButton = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','pushbutton', ...
%     'Enable','on', ...
%     'Units', 'normalized', ...
%     'Position', [.7, .31, control_button_x, control_button_y], ...
%     'String','Load', ...
%     'Callback',{@load_button_cb, obj, parentStruct, panelIndex});

% %% Select devices section
% 
% deviceName = fieldnames(obj.devices);
% devicePD = cell(length(deviceName)+1, 1);
% devicePD{1} = '<Device>';
% for i = 1:length(deviceName)
%     devicePD{i+1} = obj.devices.(deviceName{i}).Name;
% end
% 
% % Current string
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDeviceString = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','text', ...
%     'BackgroundColor',[0.9 0.9 0.9 ], ...
%     'HorizontalAlignment','left', ...
%     'Units', 'normalized', ...
%     'Position', [0.04, .17, .2, .1], ...
%     'String','Current device:', ...
%     'FontSize', 9);
% 
% currentDeviceVal = find(strcmp(obj.chip.CurrentLocation, devicePD));
% if(isempty(currentDeviceVal))
%     currentDeviceVal = 1;
% end
% % Current device popup menu
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDevicePD = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style', 'popup', ...
%     'Enable', 'on', ...
%     'Units', 'normalized', ...
%     'String', devicePD, ...
%     'Value', currentDeviceVal, ...
%     'Position', [0.26, 0.23, 0.35, 0.05], ...
%     'CallBack', {@current_device_assign_cb, obj, parentStruct, panelIndex});
% 
% % Move to string
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.moveToString = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style','text', ...
%     'BackgroundColor',[0.9 0.9 0.9 ], ...
%     'HorizontalAlignment','left', ...
%     'Units', 'normalized', ...
%     'Position', [0.04, .03, .2, .1], ...
%     'String','Move to device:', ...
%     'FontSize', 9);
% 
% % Move to device popup menu
% obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.targetDevicePD = uicontrol(...
%     'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
%     'Style', 'popup', ...
%     'Enable', 'on', ...
%     'Units', 'normalized', ...
%     'String', devicePD, ...
%     'Position', [0.26, 0.09, 0.35, 0.05]);

% Abort button
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.abort = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable','on', ...
    'Units', 'normalized', ...
    'Position', [.7, .55, control_button_x, control_button_y], ...
    'String','Abort', ...
    'Callback',{@abort_button_cb, obj, parentStruct, panelIndex});

% Fine Align button
obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.fineAlign = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.mainpanel, ...
    'Style','pushbutton', ...
    'Enable','off', ...
    'Units', 'normalized', ...
    'Position', [.7, .30, control_button_x, control_button_y], ...
    'String','Fine Align', ...
    'Callback',{@fine_align_button_cb, obj, parentStruct, panelIndex});

end

%% Callback Functions
function dXLeftButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dXStepSizeOC, 'String'));
obj.instr.fiberStage.move_x(distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um to the left']);
obj.msg(msg);
end

function dXRightButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dXStepSizeOC, 'String'));
obj.instr.fiberStage.move_x(-distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um to the right']);
obj.msg(msg);
end

function dSettingsOptical_cb(~, ~, obj)
obj.instr.fiberStage.settingsWin;
end

function dYLeftButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dYStepSizeOC, 'String'));
obj.instr.fiberStage.move_y(distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um forward']);
obj.msg(msg);
end

function dYRightButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dYStepSizeOC, 'String'));
obj.instr.fiberStage.move_y(-distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um backward']);
obj.msg(msg);
end

% function CalibrateOpticalStage_cb(~, ~, obj)
% obj.instr.fiberStage.calibrate;
% msg = strcat(obj.instr.fiberStage.Name, ': successfully calibrated.');
% obj.msg(msg);
% end
% 
function dZLeftButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZStepSizeOC, 'String'));
obj.instr.fiberStage.move_z(distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um down']);
obj.msg(msg);
end

function dZRightButtonOC_cb(~, ~, obj, parentStruct, panelIndex)
distance = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZStepSizeOC, 'String'));
obj.instr.fiberStage.move_z(-distance);
msg = strcat([obj.instr.fiberStage.Name,':moved ',num2str(distance),' um up']);
obj.msg(msg);
end

function dyRotationLeftOC_cb(~, ~, obj, parentStruct, panelIndex)
degree = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dyRotationStepSizeOC, 'String'));
obj.instr.fiberStage.move_xRotation(degree);
msg = sprintf('%s: moved %.1f%c clockwise', obj.instr.fiberStage.Name, degree, char(176));
obj.msg(msg);
end

function dxRotationRightOC_cb(~, ~, obj, parentStruct, panelIndex)
degree = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dyRotationStepSizeOC, 'String'));
obj.instr.fiberStage.move_xRotation(-degree);
msg = sprintf('%s: moved %.1f%c counter-clockwise', obj.instr.fiberStage.Name, degree, char(176));
obj.msg(msg);
end

function dzRotationLeftOC_cb(~, ~, obj, parentStruct, panelIndex)
degree = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dzRotationStepSizeOC, 'String'));
obj.instr.fiberStage.move_zRotation(-degree);
msg = sprintf('%s: moved %.1f%c clockwise', obj.instr.fiberStage.Name, degree, char(176));
obj.msg(msg);
end

function dzRotationRightOC_cb(~, ~, obj, parentStruct, panelIndex)
degree = str2double(get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dzRotationStepSizeOC, 'String'));
obj.instr.fiberStage.move_zRotation(degree);
msg = sprintf('%s: moved %.1f%c counter-clockwise', obj.instr.fiberStage.Name, degree, char(176));
obj.msg(msg);
end

% function LockOpticalStage_cb(hObject, ~, obj, parentStruct, panelIndex)
% if strcmp('Lock Z', get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dLockOpticalStage, 'String'))
%     set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZLeftButtonOC, 'Enable', 'off')
%     set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZRightButtonOC, 'Enable', 'off')
%     set(hObject, 'String', 'Unlock Z');
% elseif strcmp('Unlock Z', get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dLockOpticalStage, 'String'))
%     set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZLeftButtonOC, 'Enable', 'on')
%     set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.dZRightButtonOC, 'Enable', 'on')
%     set(hObject, 'String', 'Lock Z');
% end
% end
% 
% function current_device_assign_cb(hObject, ~, obj, parentStruct, panelIndex)
% currentDeviceIndex = get(hObject, 'Value');
% if currentDeviceIndex ~= 1
%     devicePD = get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDevicePD, 'String');
%     % Get the current Device
%     % and send the location to chip object
%     currentDevice = obj.devices.(devicePD{currentDeviceIndex});
%     obj.chip.CurrentLocation = currentDevice.Name;
% end
% end

function abort_button_cb(~, ~, obj, parentStruct, panelIndex)
    obj.instr.fiberStage.abortMotion();
end

function fine_align_button_cb(~, ~, obj, parentStruct, panelIndex)
devicePD = get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDevicePD, 'String'); % It doesn't matter which one to use
% Get the current Device Name
currentDeviceIndex = get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDevicePD, 'Value');
currentDeviceName = devicePD{currentDeviceIndex};
% Get the target Device Name
targetDeviceIndex = get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.targetDevicePD, 'Value');
targetDeviceName = devicePD{targetDeviceIndex};

if (currentDeviceIndex ~= 1 && targetDeviceIndex ~= 1)
    % Get Current and Target Devices
    currentDevice = obj.devices.(currentDeviceName);
    targetDevice = obj.devices.(targetDeviceName);
    % Move to Target Device
    moveToDevice(obj, currentDevice, targetDevice);
    newDeviceIndex = get(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.targetDevicePD, 'Value');
    set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.currentDevicePD, 'Value', newDeviceIndex);
elseif (currentDeviceIndex == 1 && targetDeviceIndex ~=1)
    %get target device
    targetDevice = obj.devices.(targetDeviceName);
    try
        obj.instr.fiberStage.moveTo(targetDevice.X, targetDevice.Y);
    catch ME
        obj.msg(ME.message)
        rethrow(ME)
    end
else
    obj.msg('Please choose proper devices.');
end
end

% function eject_button_cb(hObject, ~, obj, parentStruct, panelIndex)
% obj.instr.fiberStage.eject();
% % set(hObject, 'Enable', 'off');
% % set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.loadButton, 'Enable', 'on')
% end
% 
% function load_button_cb(hObject, ~, obj, parentStruct, panelIndex)
% obj.instr.fiberStage.load();
% % set(hObject, 'Enable', 'off');
% % set(obj.gui.(parentStruct)(panelIndex).edgeCoupledStageUI.ejectButton, 'Enable', 'on')
% end
